# Generated by Django 2.1.15 on 2020-02-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='file_path',
            field=models.FileField(upload_to='%Y/%m/%d/', verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='filemanager',
            name='name',
            field=models.CharField(max_length=200, verbose_name='文件名'),
        ),
    ]
