# Generated by Django 2.1.15 on 2020-02-17 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200212_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100, verbose_name='板块标题')),
                ('section_base_description', models.CharField(max_length=256, verbose_name='基本描述')),
                ('section_name', models.CharField(help_text='用于帮助页面组合板块详情对应的url', max_length=20, verbose_name='板块名')),
                ('section_img', models.CharField(blank=True, max_length=200, verbose_name='封面图片地址')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '更多板块',
                'verbose_name_plural': '更多板块',
                'ordering': ['-create_time'],
            },
        ),
    ]
