# Generated by Django 2.2.10 on 2020-05-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_extrasection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraSection',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=1, verbose_name='文章状态：0未发布，1发布'),
        ),
    ]
