# Generated by Django 2.2.10 on 2020-05-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200512_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, '发布'), (0, '草稿')], default=1, verbose_name='发布状态'),
        ),
    ]
